CREATE TABLE IF NOT EXISTS quota_ledger (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  api_key_id BIGINT UNSIGNED NOT NULL,
  period VARCHAR(32) NOT NULL,
  dedupe_id VARCHAR(128) NOT NULL,
  endpoint VARCHAR(32) NULL,
  action VARCHAR(64) NULL,
  reserve_units BIGINT NOT NULL DEFAULT 0,
  finalized_units BIGINT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  expires_at DATETIME NULL,
  UNIQUE KEY uq_quota_ledger_api_key_dedupe (api_key_id, dedupe_id),
  KEY idx_quota_ledger_status_expires (status, expires_at),
  KEY idx_quota_ledger_api_key_id (api_key_id),
  KEY idx_quota_ledger_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE quota_ledger
  ADD COLUMN IF NOT EXISTS api_key_id BIGINT UNSIGNED NOT NULL AFTER id,
  ADD COLUMN IF NOT EXISTS period VARCHAR(32) NOT NULL AFTER api_key_id,
  ADD COLUMN IF NOT EXISTS dedupe_id VARCHAR(128) NOT NULL AFTER period,
  ADD COLUMN IF NOT EXISTS endpoint VARCHAR(32) NULL AFTER dedupe_id,
  ADD COLUMN IF NOT EXISTS action VARCHAR(64) NULL AFTER endpoint,
  ADD COLUMN IF NOT EXISTS reserve_units BIGINT NOT NULL DEFAULT 0 AFTER action,
  ADD COLUMN IF NOT EXISTS finalized_units BIGINT NOT NULL DEFAULT 0 AFTER reserve_units,
  ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL AFTER finalized_units,
  ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER status,
  ADD COLUMN IF NOT EXISTS updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at,
  ADD COLUMN IF NOT EXISTS expires_at DATETIME NULL AFTER updated_at,
  ADD UNIQUE KEY uq_quota_ledger_api_key_dedupe (api_key_id, dedupe_id),
  ADD KEY idx_quota_ledger_status_expires (status, expires_at),
  ADD KEY idx_quota_ledger_api_key_id (api_key_id),
  ADD KEY idx_quota_ledger_created_at (created_at);
