CREATE TABLE IF NOT EXISTS alert_rules (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  metric_key VARCHAR(64) NOT NULL,
  scope_json TEXT NULL,
  operator VARCHAR(8) NOT NULL DEFAULT '>',
  threshold DOUBLE NOT NULL DEFAULT 0,
  for_sec INT UNSIGNED NOT NULL DEFAULT 0,
  eval_interval_sec INT UNSIGNED NOT NULL DEFAULT 10,
  cooldown_sec INT UNSIGNED NOT NULL DEFAULT 0,
  severity VARCHAR(16) NOT NULL DEFAULT 'warn',
  channels_json TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alert_state (
  rule_id INT UNSIGNED NOT NULL PRIMARY KEY,
  state VARCHAR(16) NOT NULL DEFAULT 'OK',
  last_change_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_fire_at DATETIME NULL,
  last_eval_at DATETIME NULL,
  pending_since DATETIME NULL,
  ack_until DATETIME NULL,
  silence_until DATETIME NULL,
  last_snapshot_path TEXT NULL,
  last_message TEXT NULL,
  last_value DOUBLE NULL,
  CONSTRAINT fk_alert_state_rule FOREIGN KEY (rule_id) REFERENCES alert_rules(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS alert_events (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  rule_id INT UNSIGNED NOT NULL,
  state VARCHAR(16) NOT NULL,
  value DOUBLE NULL,
  message TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_alert_events_rule (rule_id),
  CONSTRAINT fk_alert_events_rule FOREIGN KEY (rule_id) REFERENCES alert_rules(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lease_locks (
  name VARCHAR(64) NOT NULL PRIMARY KEY,
  owner_id VARCHAR(128) NOT NULL,
  lease_until DATETIME NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
