CREATE TABLE IF NOT EXISTS usage_monthly (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  api_key_id BIGINT UNSIGNED NOT NULL,
  period VARCHAR(32) NOT NULL,
  used_files BIGINT NULL DEFAULT 0,
  used_bytes BIGINT NULL DEFAULT 0,
  total_calls BIGINT NULL DEFAULT 0,
  total_files_processed BIGINT NULL DEFAULT 0,
  h2i_calls BIGINT NULL DEFAULT 0,
  h2i_files BIGINT NULL DEFAULT 0,
  image_calls BIGINT NULL DEFAULT 0,
  image_files BIGINT NULL DEFAULT 0,
  pdf_calls BIGINT NULL DEFAULT 0,
  pdf_files BIGINT NULL DEFAULT 0,
  tools_calls BIGINT NULL DEFAULT 0,
  tools_files BIGINT NULL DEFAULT 0,
  bytes_in BIGINT NULL DEFAULT 0,
  bytes_out BIGINT NULL DEFAULT 0,
  errors BIGINT NULL DEFAULT 0,
  last_error_code VARCHAR(64) NULL,
  last_error_message TEXT NULL,
  last_request_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_usage_monthly_api_key_id (api_key_id),
  KEY idx_usage_monthly_period (period),
  KEY idx_usage_monthly_api_key_period (api_key_id, period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE usage_monthly
  ADD COLUMN IF NOT EXISTS api_key_id BIGINT UNSIGNED NOT NULL AFTER id,
  ADD COLUMN IF NOT EXISTS period VARCHAR(32) NOT NULL AFTER api_key_id,
  ADD COLUMN IF NOT EXISTS used_files BIGINT NULL DEFAULT 0 AFTER period,
  ADD COLUMN IF NOT EXISTS used_bytes BIGINT NULL DEFAULT 0 AFTER used_files,
  ADD COLUMN IF NOT EXISTS total_calls BIGINT NULL DEFAULT 0 AFTER used_bytes,
  ADD COLUMN IF NOT EXISTS total_files_processed BIGINT NULL DEFAULT 0 AFTER total_calls,
  ADD COLUMN IF NOT EXISTS h2i_calls BIGINT NULL DEFAULT 0 AFTER total_files_processed,
  ADD COLUMN IF NOT EXISTS h2i_files BIGINT NULL DEFAULT 0 AFTER h2i_calls,
  ADD COLUMN IF NOT EXISTS image_calls BIGINT NULL DEFAULT 0 AFTER h2i_files,
  ADD COLUMN IF NOT EXISTS image_files BIGINT NULL DEFAULT 0 AFTER image_calls,
  ADD COLUMN IF NOT EXISTS pdf_calls BIGINT NULL DEFAULT 0 AFTER image_files,
  ADD COLUMN IF NOT EXISTS pdf_files BIGINT NULL DEFAULT 0 AFTER pdf_calls,
  ADD COLUMN IF NOT EXISTS tools_calls BIGINT NULL DEFAULT 0 AFTER pdf_files,
  ADD COLUMN IF NOT EXISTS tools_files BIGINT NULL DEFAULT 0 AFTER tools_calls,
  ADD COLUMN IF NOT EXISTS bytes_in BIGINT NULL DEFAULT 0 AFTER tools_files,
  ADD COLUMN IF NOT EXISTS bytes_out BIGINT NULL DEFAULT 0 AFTER bytes_in,
  ADD COLUMN IF NOT EXISTS errors BIGINT NULL DEFAULT 0 AFTER bytes_out,
  ADD COLUMN IF NOT EXISTS last_error_code VARCHAR(64) NULL AFTER errors,
  ADD COLUMN IF NOT EXISTS last_error_message TEXT NULL AFTER last_error_code,
  ADD COLUMN IF NOT EXISTS last_request_at DATETIME NULL AFTER last_error_message,
  ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER last_request_at,
  ADD COLUMN IF NOT EXISTS updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at,
  ADD KEY idx_usage_monthly_api_key_id (api_key_id),
  ADD KEY idx_usage_monthly_period (period),
  ADD KEY idx_usage_monthly_api_key_period (api_key_id, period);
