CREATE TABLE IF NOT EXISTS subscription_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  event_id VARCHAR(190) NOT NULL,
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  normalized_event VARCHAR(64) NULL,
  wp_user_id BIGINT NULL,
  customer_email VARCHAR(190) NULL,
  subscription_id VARCHAR(190) NULL,
  order_id VARCHAR(190) NULL,
  plan_slug VARCHAR(190) NULL,
  valid_from DATETIME NULL,
  valid_until DATETIME NULL,
  decision VARCHAR(32) NULL,
  api_key_id BIGINT NULL,
  error_message TEXT NULL,
  payload_json JSON NULL,
  UNIQUE KEY uniq_subscription_events_event_id (event_id),
  KEY idx_subscription_events_received_at (received_at),
  KEY idx_subscription_events_decision (decision),
  KEY idx_subscription_events_customer_email (customer_email),
  KEY idx_subscription_events_subscription_id (subscription_id),
  KEY idx_subscription_events_order_id (order_id),
  KEY idx_subscription_events_wp_user_id (wp_user_id),
  KEY idx_subscription_events_api_key_id (api_key_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE subscription_events
  ADD COLUMN IF NOT EXISTS event_id VARCHAR(190) NOT NULL AFTER id,
  ADD COLUMN IF NOT EXISTS received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER event_id,
  ADD COLUMN IF NOT EXISTS normalized_event VARCHAR(64) NULL AFTER received_at,
  ADD COLUMN IF NOT EXISTS wp_user_id BIGINT NULL AFTER normalized_event,
  ADD COLUMN IF NOT EXISTS customer_email VARCHAR(190) NULL AFTER wp_user_id,
  ADD COLUMN IF NOT EXISTS subscription_id VARCHAR(190) NULL AFTER customer_email,
  ADD COLUMN IF NOT EXISTS order_id VARCHAR(190) NULL AFTER subscription_id,
  ADD COLUMN IF NOT EXISTS plan_slug VARCHAR(190) NULL AFTER order_id,
  ADD COLUMN IF NOT EXISTS valid_from DATETIME NULL AFTER plan_slug,
  ADD COLUMN IF NOT EXISTS valid_until DATETIME NULL AFTER valid_from,
  ADD COLUMN IF NOT EXISTS decision VARCHAR(32) NULL AFTER valid_until,
  ADD COLUMN IF NOT EXISTS api_key_id BIGINT NULL AFTER decision,
  ADD COLUMN IF NOT EXISTS error_message TEXT NULL AFTER api_key_id,
  ADD COLUMN IF NOT EXISTS payload_json JSON NULL AFTER error_message,
  ADD UNIQUE KEY uniq_subscription_events_event_id (event_id),
  ADD KEY idx_subscription_events_received_at (received_at),
  ADD KEY idx_subscription_events_decision (decision),
  ADD KEY idx_subscription_events_customer_email (customer_email),
  ADD KEY idx_subscription_events_subscription_id (subscription_id),
  ADD KEY idx_subscription_events_order_id (order_id),
  ADD KEY idx_subscription_events_wp_user_id (wp_user_id),
  ADD KEY idx_subscription_events_api_key_id (api_key_id);
